name = "SimplyRefined"
author = "Cccc_"
version = "v2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b89fc27a15f37956e2840ce2808c0d9afd7cdb2a7e046e0cd26bfd2f4cea6e23"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"
