name = "SimplyRefined"
author = "Cccc_"
version = "v2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e73fa33f192978138b15ed3d46063e0f450c2705c607a8e76b69d3ef664e46ca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
