name = "SimplyRefined"
author = "Cccc_"
version = "v2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d7bfba5c0ab008dc5a4f613f9930e1ed0b7242a5d6e9f5395db85f8f5d2b89c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
