name = "SimplyRefined"
author = "Cccc_"
version = "v2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4140302884b37b62bb8c78a0bbf15044be08d446921bb1d83fa5d5544b277b01"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
