name = "SimplyRefined"
author = "Cccc_"
version = "v2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8d2186c550ad3e8fb1e783dbb81ed529aaa0ec28e0aee43c2f69f548c4d643f"

[versions]
fabric = "0.17.3"
minecraft = "1.21.4"
